<div class="fieldset-wrapper-title">
    <span class="title"><?=__('Cashback history')?></span>
</div>
<table class="admin__table-secondary">
    <thead >
    <tr>
        <th>
            <h2><?= __("Operation") ?> </h2>
        </th>
        <th>
            <h2><?= __('Remains Coins') ?></h2>
        </th>
        <th>
            <h2><?= __('Created At') ?> </h2>
        </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($block->getCollectionHistory() as $item) : ?>
        <tr>
            <td><?= $item->getData('operation'); ?> <br></td>
            <td><?= $item->getData('remain_coin'); ?> <br></td>
            <td><?= $item->getData('created_at'); ?> <br></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
