<?php /** @var \Kirill\Cash\Block\Bonus\History $block */ ?>
<table class="data table">
    <thead>
    <tr>
        <th>
            <?= $block->escapeHTML(__("Operation")); ?>
        </th>
        <th>
            <?= $block->escapeHTML(__('Remains Coins')); ?>
        </th>
        <th>
            <?= $block->escapeHTML(__('Operation Sum')); ?>
        </th>
        <th>
            <?= $block->escapeHTML(__('Created At')); ?>
        </th>
    </tr>
    </thead>
    <tbody>
    <?php $historyView = $block->getHistoryView();
    foreach ($historyView->getBonusHistory() as $item) :?>
        <tr>
            <?php //$this->escaper->escapeHTML()?>
            <td><?= $block->escapeHtml($item->getData('operation')); ?> <br></td>
            <td><?= $block->escapeHtml($item->getData('remain_coin')); ?> <br></td>
            <td><?= $block->escapeHtml($item->getData('sum')); ?> <br></td>
            <td><?= $block->escapeHtml($item->getData('created_at')); ?> <br></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
